spring:
  application:
    name: toDoList

  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name?useSSL=false&serverTimezone=UTC
    username: your_db_user
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
